### ISSUE TITLE
Tickets: colorização por privilégio do grupo

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/sapood#13]
Deixou de funcionar:

 - [x] cores nos ícones from/to no cabeçalho de cada ticket
 - [x] cores nos autores (e destinatário) das mensagens dos tickets

Fiz um `git bisect` e parece que isso quebrou em 702799b258ef7a3f86c206ff76878d485ea38a66.

**Comment by lehonma** [comment]
Fixed on Commit 1d8405be
