### ISSUE TITLE
Sumários do trabalho de um supervisor ou pesquisador

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/sapood#14]
O filtro não funciona, ou há algum problema na geração de surveys.

**Comment by jonasmalacofilho** [comment]
O filtro do sumário "status" já funciona; no histórico o problema ainda persiste.

**Comment by lehonma** [comment]
Fixed args parser

**Comment by lehonma** [comment]
(@commit 7f55e105)
