### ISSUE TITLE
Não há mensagem para erro de login

### ISSUE THREAD

**Issue by aszasz** [jonasmalacofilho/sapood#17]
Quando o usuário entra a senha ou nome errado o sistema limpa o campo de senha... sem mensagem nenhuma (mas o Chrome preenche com a senha (se pediu para decorar) e o usuário não percebe). Seria interessante escrever algo como "login e/ou senha inválido(s)" como resposta.

**Comment by jonasmalacofilho** [comment]
Yeap.  Precisamos de mensagens de erros em outros lugares também.

Para começar, pensei em usar página para o erro 500 _também_ como template, e escrever nele as mensagens de erro.  Algo como um `Web.redirect` para uma rota `/error?msg=...`; daí o usuário pode usar o "voltar" para tentar outra vez, presumivelmente só depois de ter corrigido o problema.
