### ISSUE TITLE
Log in required twice

### ISSUE THREAD

**Issue by aszasz** [jonasmalacofilho/sapood#26]
This happens to me always when I first try to enter in a new build on robrt (in Chrome, Firefox, Safari on iPhone,...), at first I thought it was my mistake in typing... but now I suspect it is not

**Comment by jonasmalacofilho** [comment]
Reproduced on sapo.robrt.io (tora), not on local development server.

Seems that the user is successfully logged in (and has access to links on the navbar), but still sees the login page.

**Comment by jonasmalacofilho** [comment]
Reproduced on local development server by forcing a redirect to `/login?redirect=%3F`

**Comment by jonasmalacofilho** [comment]
Fixed and deployed.
