### ISSUE TITLE
Fechamento de Ticket pelo Telefonista

### ISSUE THREAD

**Issue by aszasz** [jonasmalacofilho/sapood#28]
Para que o telefonista possa fechar o ticket é necessário que ele tenha feito a conferência (i.e. habilitado o telefone e marcado "V" or "X"). A meu ver as alternativas são:
   - manter o botão desabilitado enquanto a condição não for atendida (via JS)
   - retornar warning caso ele clique em fechar sem atender a condição (via route)

**Comment by jonasmalacofilho** [comment]
Desabilitar o botão (não precisa sequer ser via JS, dado que a conferência força um reload) parece o mais apropriado na UI.

(de qualquer forma, a rota também precisa implementar a mesma restrição)

**Comment by lehonma** [comment]
0ca5f541
