### ISSUE TITLE
Mostrar para cada pesquisa se há tickets abertos

### ISSUE THREAD

**Issue by aszasz** [jonasmalacofilho/sapood#30]
Solicitação da Logit
Um envelope/bilhete desenhado no cabeçalho ao lado do telefone?

**Comment by aszasz** [comment]
Verificar que esse cabeçalho se extenda aos tickets e pesquisa, o que deve acontecer automaticamente se for colocado no `sapo.view.Util.status( )`...

**Comment by jonasmalacofilho** [comment]
Não acho que mostrar se há algum ticket aberto para uma dada pesquisa faz sentido na view de tickets, só na de pesquisas.  Mesmo assim, se simplesmente reutilizado na view de tickets (implementado em `sapo.view.Util.status`) esse ícone não diria nada sobre o estado (aberto/fechado) do ticket atual, que é a necessidade que surge com mostrar tickets abertos e fechados numa mesma página.

Ainda...  Em #32, achei que visualmente poderia ser o mesmo símbolo, mas já não tenho tanta certeza.  Usar o mesmo símbolo _pode_ gerar confusão, com ele num lugar significando "há tickets abertos" e em outro "esse é um ticket aberto".
