### ISSUE TITLE
Novo filtro em tickets 

### ISSUE THREAD

**Issue by aszasz** [jonasmalacofilho/sapood#32]
Mudar tickets filter label de "Para todos" para "todos"
Logit solicita filtro por usuário... descrição enviada para Logit da funcionalidade:
**Listagem de tickets:**
Em função do seu privilégio, usuários podem listar tickets:
  - De/Para si (Supervisor);
  - De/Para si e Para grupo (Telefonista);
  - Todos os tickets (Coordenação).

Os tickets poderão ser filtrados por:
  - Estado: aberto, fechado, todos;
  - De/para grupo ou usuário (restrito aos privilégios do usuário).

**Comment by jonasmalacofilho** [comment]
?

**Comment by aszasz** [comment]
Lendo as requisções da Logit, achei que o problema "todos" para "todos" seria resolvido de brinde ao tratar do issue  maior... Eu deveria ter aberto um novo issue?

**Comment by jonasmalacofilho** [comment]
Não entendi bem o que é o "todos" para "todos".

**Comment by aszasz** [comment]
está escrito `para todos`, e se escrevermos apenas  `todos`... a linguagem  funciona sempre (querendo dizer "para mim + para meu grupo"... enquanto para todos pode presumir incluir mais gente...

**Comment by jonasmalacofilho** [comment]
Adiantando...

Vejo no texto da logit duas coisas independentes (exceto por serem depois combinadas):

 1. problemas de nomenclatura no "Para todos", "Para grupo", "De/para mim" (verifique se está ha o "de/" no seu commit); renomear "para todos" para "todos" resolve isso muito bem mesmo, é quase brilhante na simplicidade! thanks! _(já implementei, só não dei push porque não quero fechar o issue com ele)_
 2. ver tickets abertos e fechados simultaneamente; pode ser feito, mas seu uso é menos frequente que abertos `xor` fechados e ele exige a incluir em cada ticket header (colapsado) se ele está aberto ou não

**Comment by jonasmalacofilho** [comment]
Sim, você estava certo, isso é resolvido de brinde.  Mesmo assim, acho o título "Mudar ..." melhor.  Vou renomear e dar push com o commit que já fecha esse ticket, ok?

**Comment by aszasz** [comment]
Em outro issue, a Logit solicitou a colocação de um indicador se há um ticket aberto... ao que sugeri colocarmos um envelope no cabeçalho (ao lado do telefone, cifrão e checks).
Se isso for feito, o envelope indicará ticket aberto... ausência dele indicará ticket fechado.

**Comment by jonasmalacofilho** [comment]
Sim, podemos podemos _estender_ #30 para cabeçalhos dos tickets também.

Sobre o "abertos" `or` "fechados", você abre outro ticket?

**Comment by aszasz** [comment]
Abro.

**Comment by jonasmalacofilho** [comment]
Thanks!
