### ISSUE TITLE
Novo filtro em tickets, por user

### ISSUE THREAD

**Issue by aszasz** [jonasmalacofilho/sapood#33]
A solicitação da Logit:
>  incluir filtro por pesquisador ou por usuários especificos

Descrição da funcionalidade para a Logit:

> **Listagem de tickets:**
> Em função do seu privilégio, usuários podem listar tickets:
>    - De/Para si (Supervisor);
>    - De/Para si e Para grupo (Telefonista);
>    - Todos os tickets (Coordenação).
>
> Os tickets poderão ser filtrados por:
>  - Estado: aberto, fechado, todos;
>  - De/para grupo ou usuário (restrito aos privilégios do usuário).

**Comment by jonasmalacofilho** [comment]
A Logit quer filtrar tickets nos quais um usuário específico (ou um grupo específico, mas sem nenhuma relação com o usuário logado) foi incluído?

Ainda, por pesquisador?  Como ele não tem acesso aos tickets, imagino que seja pelo pesquisador da pesquisa, mas nisso há um gap considerável: essa informação está há dois níveis de indireção do ticket.  Se mesmo necessário, acho melhor permitirmos filtrar pesquisas por pesquisador `AND` com tickets abertos; isso faz mais sentido em relação a como o resto da interface funciona e de lá, se consegue ver os tickets individualmente.

**Comment by jonasmalacofilho** [comment]
Anotando: vamos implementar opções adicionais a "de/para mim", para outros autores ou destinatários  possíveis.
