### ISSUE TITLE
Tickets: ver abertos e fechados simultaneamente

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/sapood#34]
Parte de #32 (e #30) trata disso.

@aszasz: não me enganei, certo? Esse é um dos feature requests da logit?

@craice: essencialmente o problema é que, com tickets abertos e fechados numa mesma página, precisamos ter alguma maneira de identificar em qual estado cada um está.  Considerou-se reutilizar a simbologia de #30, mas me ocorre que isso _pode_ gerar confusão, já que existir um ticket aberto para uma pesquisa não tem praticamente nada em comum com se um dado ticket está ou não aberto.  O que você acha?

**Comment by jonasmalacofilho** [comment]
Atualmente mostramos `abertos XOR fechados`; a Logit gostaria de ver `(abertos XOR fechados) XOR (abertos OR fechados)`.

**Comment by jonasmalacofilho** [comment]
@aszasz: como a Logit gostaria de usar esse feature?  Isoladamente ele é bem pouco útil...

**Comment by aszasz** [comment]
Eu não sei como a Logit gostaria de usar esse feature ... na verdade acho que não vai usar... tickets fechados are not of concern (essa é a idéia dos tickets). Pode ser que eles achem que isso é mesmo uma métrica de produtividade (o que não faz sentido, porque não dá para inferir nada sobre a qualidade do ticket ou da solução com base no número de tickets abertos e fechados... mesmo porque não damos os totais) 
Acho mais fácil que discutir isso, dar o que foi pedido... uma alteração na cor de fundo no cabeçalho, como o abaixo, funcionaria?
'<div class="panel-heading" role="tab" id="HeadTicket(: ticket.id :)" (:if ticket.closed_at == null:) style="color: #123(: end :)>

**Comment by jonasmalacofilho** [comment]
Não fiz um preview manual disso mas sim, algo com cores (eu acho que) pode funcionar... Deixar todo o ticket (cabeçalho e corpo) "faded-out" talvez.

**Comment by craice** [comment]
background-color: #DDD; nesse elemento funciona.

**Comment by lehonma** [comment]
Posso converter todos os tickets fechados com esta cor de cabeçalho (definido pelo craice), ou devo implementar isso somente para o caso de mostrar ambos?

**Comment by jonasmalacofilho** [comment]
Acho que todos, assim "estabelece uma linguagem" (thanks, Craice).

**Comment by lehonma** [comment]
Check commit 7d86bb27

**Comment by jonasmalacofilho** [comment]
Aparentemente isso quebra a combinação "De/para mim" + "Fechados" (para a Alice).  Can you check that?

**Comment by jonasmalacofilho** [comment]
Ok.  Falei errado.  O problema parece estar em "De/para mim" + "Todos"; tickets aleatórios estão aparecendo, até duplicados.

**Comment by lehonma** [comment]
Arrumei a query
