### ISSUE TITLE
Pesquisa individual: pequenas correções

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/sapood#4]
- ver tickets
     - [x] corrigir a url
     - . ~~só supervisor e super-usuários~~
 - [x] abrir tickets
 - [x] modal de mudar flags
 - [x] remover `target=_blank` de ver tickets

**Comment by craice** [comment]
- [ ] corrigir hora da saída e chegada. (15:8)

**Comment by jonasmalacofilho** [comment]
- [ ] `Util.status` precisa ser atualizado
 - [ ] `phoned` parece com problemas

(pode ter sido problema do merge)

**Comment by jonasmalacofilho** [comment]
(soon) closed by merging #27
