### ISSUE TITLE
Tickets: pequenas alterações

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/sapood#5]
- [x] usar Survey, não NewSurvey
 - [x] flags da pesquisa
 - [x] `group.name`, não `group.group_name`
 - [x] sumário da pesquisa (reutilizar da lista de pesquisas)
 - [x] transformar filtro de usuário _no modal_ em campo único (como em pagamentos); só mostrar supervisores e super-usuários
 - [x] verificar permissão de acesso a: incluir, responder, fechar
 - [x] mensagem automáticas de fechamento de ticket
 - [x] combar pesquisa no filtro (evita flag de fechado, e melhora a busca de tickets)
 - [x] tickets fechados: reabrir, não responder; não incluir
 - [x] mensagem automáticas de reabertura de ticket
 - [x] paginação
 - [x] Incluir pessoas no ticket

__No futuro:__

 - mensagens automáticas alterações na pesquisa

**Falta um**: "???? filtrando"

**Comment by jonasmalacofilho** [comment]
- [ ] limitar o número de ticket subscriptions para um par ticket,group ou ticket,user a 1

**Comment by jonasmalacofilho** [comment]
- [ ] filtro: "para mim" mostrando tickets não relacionados ([exemplo](http://localhost:2000/tickets?recipient=individual&state=open&survey=))
 - [ ] filtro: "fechados" + pesquisa não faz o filtro necessário ([exemplo](http://localhost:2000/tickets?recipient=all&state=closed&survey=2))

**Comment by lehonma** [comment]
Fixed at commit e96f464f
